### ISSUE TITLE
yarn run test fails

### ISSUE THREAD

**Issue by alepi** [etesync/etebase-js#39]
Hi,

I am evaluating etebase as a possible backend for something I am working on. Congrats for creating all this by the way as it looks super cool :-)

I managed to deploy my own server instance locally which seems to work fine. I can connect to admin, create new users, then log them in and create a calendar with etebase-web.

When I test etebase-js with that instance I get the following results:

Test Suites: 3 failed, 2 passed, 5 total
Tests:       25 failed, 1 skipped, 10 passed, 36 total
Snapshots:   0 total
Time:        5.38s
Ran all test suites.

The server logs are:

INFO:     127.0.0.1:50912 - "POST /api/v1/authentication/signup/ HTTP/1.1" 409 Conflict
INFO:     127.0.0.1:50913 - "POST /api/v1/authentication/signup/ HTTP/1.1" 409 Conflict
INFO:     127.0.0.1:50914 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50915 - "GET /api/v1/authentication/is_etebase/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:50916 - "GET /api/api/v1/authentication/is_etebase/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50917 - "POST /api/api/v1/authentication/login_challenge/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50918 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50919 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50920 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50921 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50922 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50923 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50924 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50925 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50926 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50927 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50928 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50929 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50930 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50931 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50932 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50933 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50934 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50935 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50936 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50937 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50938 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50939 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50940 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50941 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50942 - "POST /api/v1/test/authentication/reset/ HTTP/1.1" 404 Not Found

Can anyone shed some light upon this issue?

**Comment by tasn** [comment]
You need to run the server in debug mode for the tests to work.

Closing as the question was answered.

**Comment by alepi** [comment]
How does one "run the server in debug mode" ?

This does not seem to make any difference regarding the failures:
DEBUG=True uvicorn etebase_server.asgi:application --port 8000 --host 0.0.0.0
