### ISSUE TITLE
 Cannot find module 'react-native-sodium'.

### ISSUE THREAD

**Issue by negue** [etesync/etebase-js#7]
Using Angular 9 - I get this error:

```
    ERROR in node_modules/etebase/dist/lib/Crypto.d.ts:3:31 - error TS2307: Cannot find module 'react-native-sodium'.
    
    3 import type rnsodiumType from "react-native-sodium";
                                    ~~~~~~~~~~~~~~~~~~~~~
```

So do I need to install react-native-sodium even if I dont use any of it?

**Comment by negue** [comment]
Current workaronud:

Add `"skipLibCheck": true` to your tsconfig `compilerOptions`

**Comment by tasn** [comment]
How are you building your module? Just using typescript as the bundler? Let me know how to reproduce it and I can fix it immediately. It's been hell trying to figure out how to make it work with all the different oddities of different compilers/bundlers.

**Comment by negue** [comment]
Sorry for the long delay.

Angular uses webpack and itself uses typescript inside.


How to reproduce:

1. https://angular.io/guide/setup-local
2. `ng new etebase-test` (just the defaults)
3. `cd etebase-test`
4. `npm install etebase -S`
5. open app.component.ts in an editor
6. add `import * as Etebase from 'etebase';` there
7. run `ng serve`
8. see the error 

The only workaround I found, is to open your `tsconfig.json` and add `skipLibCheck": true` to the `compilerOptions`

**Comment by tasn** [comment]
Weird that it fails for Angular but works here (in React and React Native, including just type checks).
Anyhow, I just pushed a new micro version with a fix. Essentially we were exposing this type for an internal function that enables us to hook in react-native implementations. We don't really need the type information (and it's indeed not available when not using react native) so just removed that.

Please try upgrading to `0.40.1` and let me know if that doesn't fix it.

**Comment by negue** [comment]
Works now 👍

**Comment by tasn** [comment]
Great! Thanks again for reporting!
