### ISSUE TITLE
Details of Local Cache

### ISSUE THREAD

**Issue by claudiojulioferraz** [etesync/etebase-js#8]
Hi! Where is the **Local Cache** stored?

_Automatically translated._

**Comment by tasn** [comment]
It's stored to a string which you can then store wherever you want. For example, https://github.com/etesync/etesync-notes/ stores it in the redux store. Others can store it in local storage. It's really up to you.

Come and join the chat at https://www.etebase.com/community-chat/ if you have any questions.
